### ISSUE TITLE
README.md 파일의 Language 부분 수정요청

### ISSUE THREAD

**Issue by HayeonKimm** [hanghae99-19/hanghae99#1]
JAVASCRIPT 부분이 전체 대문자라 문서의 통일성을 해치는 것 같아서 

JAVASCRIPT -> Javascript 변경요청 드립니다.

혹시 권지은님이 수정 가능하실까요?

**Comment by itsstacy** [comment]
수정완료 했습니다! 통일성 있고 좋네요!!

**Comment by HayeonKimm** [comment]
> 수정완료 했습니다! 통일성 있고 좋네요!!

감사합니다 지은님 수고하셨어요~!
